# Ok


1. get jira to panda DF format
2. extract features
2.1 bag of words from description, creator, reporter
3. predict priopity
4. predict time estimate/ SP estimate

In [47]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import GaussianNB
from numpy import *
from sklearn.cross_validation import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix
from sklearn.multiclass import OneVsOneClassifier
from sklearn.svm import LinearSVC
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv('apache.csv', index_col=0, skiprows=0)
df

projectCategory                       created  priority  \
issue key                                                                
ZOOKEEPER-2769       ZooKeeper  2017-04-28T19:44:50.000+0000     Major   
ZOOKEEPER-2768       ZooKeeper  2017-04-28T09:57:55.000+0000  Critical   
ZOOKEEPER-2767       ZooKeeper  2017-04-27T12:14:48.000+0000   Trivial   
ZOOKEEPER-2766       ZooKeeper  2017-04-25T10:18:42.000+0000     Major   
ZOOKEEPER-2765       ZooKeeper  2017-04-19T15:43:08.000+0000     Major   
ZOOKEEPER-2764       ZooKeeper  2017-04-19T09:54:16.000+0000     Minor   
ZOOKEEPER-2763       ZooKeeper  2017-04-19T06:34:02.000+0000     Minor   
ZOOKEEPER-2762       ZooKeeper  2017-04-18T21:57:58.000+0000     Major   
ZOOKEEPER-2761       ZooKeeper  2017-04-18T11:31:19.000+0000     Major   
ZOOKEEPER-2760       ZooKeeper  2017-04-18T07:49:07.000+0000   Blocker   
ZOOKEEPER-2759       ZooKeeper  2017-04-17T22:45:41.000+0000     Major   
ZOOKEEPER-2758       ZooKeeper  2017-04-15T06:30:58.000+0000   Trivial   
ZOOKEEPER-2757       ZooKeeper  2017-04-14T21:58:40.000+0000     Minor   
ZOOKEEPER-2756       ZooKeeper  2017-04-13T21:55:00.000+0000     Major   
ZOOKEEPER-2755       ZooKeeper  2017-04-13T04:51:04.000+0000     Major   
ZOOKEEPER-2754       ZooKeeper  2017-04-11T22:37:00.000+0000     Major   
ZOOKEEPER-2753       ZooKeeper  2017-04-11T22:17:29.000+0000     Major   
ZOOKEEPER-2752       ZooKeeper  2017-04-11T22:13:57.000+0000     Major   
ZOOKEEPER-2751       ZooKeeper  2017-04-10T17:11:26.000+0000     Minor   
ZOOKEEPER-2750       ZooKeeper  2017-04-07T19:49:09.000+0000     Major   
ZOOKEEPER-2749       ZooKeeper  2017-04-07T03:49:08.000+0000     Major   
ZOOKEEPER-2748       ZooKeeper  2017-04-06T22:03:43.000+0000     Minor   
ZOOKEEPER-2747       ZooKeeper  2017-04-06T22:01:58.000+0000     Major   
ZOOKEEPER-2746       ZooKeeper  2017-04-04T23:39:24.000+0000     Major   
ZOOKEEPER-2745       ZooKeeper  2017-04-04T21:55:38.000+0000  Critical   
ZOOKEEPER-2744       ZooKeeper  2017-04-03T02:56:15.000+0000   Trivial   
ZOOKEEPER-2743       ZooKeeper  2017-04-01T20:30:47.000+0000     Major   
ZOOKEEPER-2742       ZooKeeper  2017-03-30T15:08:49.000+0000   Trivial   
ZOOKEEPER-2741       ZooKeeper  2017-03-28T18:52:15.000+0000     Minor   
ZOOKEEPER-2740       ZooKeeper  2017-03-27T17:35:36.000+0000  Critical   
...                        ...                           ...       ...   
ZOOKEEPER-1785       ZooKeeper  2013-10-09T00:22:29.000+0000     Minor   
ZOOKEEPER-1784       ZooKeeper  2013-10-08T19:18:12.000+0000     Major   
ZOOKEEPER-1783       ZooKeeper  2013-10-07T18:01:56.000+0000     Major   
ZOOKEEPER-1782       ZooKeeper  2013-10-04T18:24:07.000+0000     Major   
ZOOKEEPER-1781       ZooKeeper  2013-10-04T01:19:27.000+0000     Minor   
ZOOKEEPER-1780       ZooKeeper  2013-10-02T18:56:10.000+0000     Minor   
ZOOKEEPER-1779       ZooKeeper  2013-10-02T18:42:57.000+0000  Critical   
ZOOKEEPER-1778       ZooKeeper  2013-10-02T17:36:16.000+0000     Minor   
ZOOKEEPER-1777       ZooKeeper  2013-10-02T10:09:42.000+0000  Critical   
ZOOKEEPER-1776       ZooKeeper  2013-10-02T10:07:01.000+0000     Major   
ZOOKEEPER-1775       ZooKeeper  2013-10-02T10:05:17.000+0000     Major   
ZOOKEEPER-1774       ZooKeeper  2013-10-01T23:14:39.000+0000   Blocker   
ZOOKEEPER-1773       ZooKeeper  2013-10-01T21:20:56.000+0000     Major   
ZOOKEEPER-1772       ZooKeeper  2013-10-01T13:43:13.000+0000     Major   
ZOOKEEPER-1771       ZooKeeper  2013-10-01T07:04:07.000+0000     Minor   
ZOOKEEPER-1770       ZooKeeper  2013-09-30T08:00:45.000+0000     Minor   
ZOOKEEPER-1769       ZooKeeper  2013-09-29T17:12:17.000+0000     Minor   
ZOOKEEPER-1768       ZooKeeper  2013-09-27T09:19:10.000+0000     Major   
ZOOKEEPER-1767       ZooKeeper  2013-09-27T01:28:05.000+0000     Minor   
ZOOKEEPER-1766       ZooKeeper  2013-09-26T04:25:11.000+0000     Minor   
ZOOKEEPER-1765       ZooKeeper  2013-09-25T22:21:01.000+0000   Trivial   
ZOOKEEPER-1764     

In [53]:

vect = TfidfVectorizer()
X = vect.fit_transform(df['summary'].values.astype('U')) 
yr = df['priority'].values.astype('U')


encoder = LabelEncoder()
encoder.fit(yr)
y = encoder.transform(yr)


array([2, 1, 4, 2, 2, 3, 3, 2, 2, 0, 2, 4, 3, 2, 2, 2, 2, 2, 3, 2, 2, 3, 2,
       2, 1, 4, 2, 4, 3, 1, 2, 2, 1, 2, 4, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 1, 1, 2, 3, 3, 2, 2, 2, 2, 2, 2, 3,
       3, 2, 2, 1, 2, 2, 2, 0, 2, 3, 3, 1, 2, 2, 2, 2, 0, 2, 3, 2, 2, 2, 2,
       2, 3, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 1, 2, 2, 3,
       2, 2, 2, 2, 2, 4, 2, 0, 2, 2, 3, 2, 0, 3, 2, 1, 2, 2, 0, 0, 2, 3, 4,
       2, 4, 3, 2, 2, 2, 3, 2, 3, 4, 2, 2, 2, 3, 4, 1, 2, 2, 2, 2, 1, 2, 2,
       2, 2, 3, 3, 2, 3, 2, 1, 2, 3, 3, 2, 0, 2, 1, 2, 2, 2, 3, 2, 1, 2, 3,
       2, 2, 3, 2, 3, 2, 0, 3, 2, 2, 2, 2, 1, 2, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 3, 4, 3, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 3, 2, 0, 2, 3, 3, 2, 2,
       2, 2, 2, 3, 3, 2, 2, 2, 1, 2, 3, 3, 2, 3, 3, 3, 2, 2, 3, 0, 3, 2, 1,
       1, 2, 2, 2, 2, 2, 3, 3, 3, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 4, 3,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 4, 2, 1, 2, 1, 3, 3, 2, 4, 2, 2,
       3, 1,

In [49]:
TEST_SIZE = 0.2
RANDOM_STATE = 0
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE)


In [50]:
y_pred = OneVsOneClassifier(LinearSVC(random_state=0)).fit(X_train, y_train).predict(X_val)
confusion_matrix(y_val, y_pred)

array([[  1,   0,  18,   1,   0],
       [  0,   0,  10,   1,   0],
       [  1,   1, 110,  12,   0],
       [  0,   0,  30,   7,   0],
       [  0,   0,   6,   1,   1]])

In [52]:
y_val

array([2, 2, 2, 4, 3, 2, 4, 2, 1, 2, 2, 2, 0, 2, 2, 0, 4, 1, 2, 2, 2, 2, 2,
       2, 2, 2, 0, 2, 1, 1, 2, 2, 2, 2, 2, 3, 0, 0, 2, 2, 2, 2, 3, 2, 2, 2,
       2, 2, 1, 2, 3, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 4, 2, 3, 2, 1, 2, 2, 1,
       2, 2, 3, 2, 2, 1, 0, 2, 3, 3, 2, 3, 2, 0, 2, 2, 3, 2, 2, 2, 3, 2, 3,
       0, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 4, 2, 2, 0, 2, 2, 2, 2, 0, 2,
       0, 0, 3, 2, 2, 3, 2, 0, 3, 3, 2, 2, 2, 3, 2, 3, 2, 2, 3, 2, 0, 3, 2,
       2, 2, 2, 2, 2, 0, 2, 2, 0, 0, 2, 4, 2, 2, 2, 2, 3, 4, 2, 2, 1, 2, 2,
       3, 3, 2, 1, 2, 1, 2, 2, 4, 2, 2, 2, 2, 3, 2, 3, 3, 0, 3, 3, 2, 3, 2,
       3, 2, 2, 2, 3, 2, 2, 2, 2, 3, 0, 3, 0, 2, 3, 2])

In [8]:
from sklearn import metrics
metrics.accuracy_score(y_val, y_pred)

0.59499999999999997

In [9]:
print(metrics.classification_report(y_val, y_pred))

             precision    recall  f1-score   support

          0       0.50      0.05      0.09        20
          1       0.00      0.00      0.00        11
          2       0.63      0.89      0.74       124
          3       0.32      0.19      0.24        37
          4       1.00      0.12      0.22         8

avg / total       0.54      0.59      0.52       200



In [ ]:
#plot
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt
from itertools import cycle
from sklearn.metrics import roc_curve, auc



In [10]:
y[:5]

array([2, 1, 4, 2, 2])

In [11]:
yr[:5]

array([u'Major', u'Critical', u'Trivial', u'Major', u'Major'], 
      dtype='<U8')

In [12]:
encoder.classes_

array([u'Blocker', u'Critical', u'Major', u'Minor', u'Trivial'], 
      dtype='<U8')

In [13]:
X_val

<200x2073 sparse matrix of type '<type 'numpy.float64'>'
	with 1657 stored elements in Compressed Sparse Row format>

In [14]:
def extract(review):
    '''extracts features from review'''
    result = {}
    for word in str(review).split():
        if word in result:
            result[word] += 1
        else:
            result[word] = 1
    return result

In [15]:
reviews = df['description']

In [16]:
X = []
y = []
words = []
# build an index of all occurring words
for review in reviews:
    for word in extract(review):
        if word not in words:
            words.append(word)


In [17]:
words

['and',
 'control',
 'into',
 'them',
 'uncompiled',
 'have',
 'in',
 'our',
 'xml',
 'We',
 'should',
 'source',
 'only',
 'precompiled',
 'under',
 'files',
 'src/docs/',
 'that',
 'docs/We',
 'documentation',
 'remove',
 'compile',
 'data,such',
 'about',
 'word',
 'we',
 'Some',
 'ideas',
 'cons,can',
 'four',
 'add',
 'command',
 'likenow/10.204.2.39:63943[1](queued=0,recved=7,sent=7,sid=0x154c32e8c2a5b8c,lop=PING,est=1483669807748,to=10000,l',
 'command1)',
 'dimension',
 'keystore',
 'exception',
 'locati',
 'for',
 'In',
 'of',
 'contains',
 'messages',
 'related',
 'truststore',
 'org.apache.zookeeper.common.X509Util.org.apache.zookeeper.common.X509Util.createSSLContext',
 'instead',
 'own',
 'is',
 'ZooKeeper',
 'When',
 'quorum,',
 'one',
 'say',
 'out',
 'finally',
 'their',
 'currently',
 'three',
 'start',
 '3',
 '2',
 'nodes',
 'ensemble',
 'node',
 'behavior:Two',
 'I',
 'nodes,',
 "I'm",
 'a',
 'comprising',
 'facing',
 '3)',
 'following',
 'the',
 "(let's",
 'modern',

In [54]:
#next method
df.shape

(1000, 7)

In [55]:
X = df.summary.values.astype('U')
X[:5]

array([u'Compiled documentation should not be under source control',
       u'Some ideas about four word command',
       u'Correct the exception messages in X509Util if truststore location or password is not configured',
       u'Quorum fails with java.io.EOFException', u'modern C++ client'], 
      dtype='<U241')

In [63]:
y =df.priority


In [64]:
y.value_counts().sort_index()

Blocker      70
Critical     67
Major       584
Minor       227
Trivial      52
Name: priority, dtype: int64

In [65]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()

In [66]:
X_train_dtm = vect.fit_transform(X_train)
X_test_dtm = vect.transform(X_test)

In [67]:
pd.DataFrame(X_train_dtm.toarray(), columns=vect.get_feature_names()).head()

06  0bytes  10  12  127  14  1576  1653  1663  1910  ...   zookeeperserver  \
0   0       0   0   0    0   0     0     0     0     0  ...                 0   
1   0       0   0   0    0   0     0     0     0     0  ...                 0   
2   0       0   0   0    0   0     0     0     0     0  ...                 0   
3   0       0   0   0    0   0     0     0     0     0  ...                 0   
4   0       0   0   0    0   0     0     0     0     0  ...                 0   

   zookeeperserverbean  zookeeperserverlistenerimpl  zookeeperservermain  \
0                    0                            0                    0   
1                    0                            0                    0   
2                    0                            0                    0   
3                    0                            0                    0   
4                    0                            0                    0   

   zookeepertest  zookeper  zookkeeper  zoookeeper  zootrace  zxid  
0              0         0           0           0         0     0  
1              0         0           0           0         0     0  
2              0         0           0           0         0     0  
3              0         0           0           0         0     0  
4              0         0           0           0         0     0  

[5 rows x 1742 columns]

In [68]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()


In [69]:
nb.fit(X_train_dtm, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [70]:
y_pred_class = nb.predict(X_test_dtm)

In [71]:
metrics.accuracy_score(y_test, y_pred_class)

0.57599999999999996

In [72]:
y_test.value_counts().head(5) / y_test.shape

Major       0.564
Minor       0.248
Blocker     0.068
Trivial     0.060
Critical    0.060
Name: priority, dtype: float64

In [73]:
metrics.confusion_matrix(y_test, y_pred_class)

array([[  2,   0,  14,   1,   0],
       [  0,   0,  13,   2,   0],
       [  0,   0, 134,   7,   0],
       [  0,   0,  54,   8,   0],
       [  0,   0,  11,   4,   0]])

In [74]:
print(metrics.classification_report(y_test, y_pred_class))

             precision    recall  f1-score   support

    Blocker       1.00      0.12      0.21        17
   Critical       0.00      0.00      0.00        15
      Major       0.59      0.95      0.73       141
      Minor       0.36      0.13      0.19        62
    Trivial       0.00      0.00      0.00        15

avg / total       0.49      0.58      0.47       250



In [75]:
#plot
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt
from itertools import cycle
from sklearn.metrics import roc_curve, auc

yp = label_binarize(y, classes=[0, 1, 2,3,4])
n_classes = yp.shape[1]

In [37]:
n_classes

5

In [83]:
fpr = dict()
tpr = dict()
roc_auc = dict()

y_test

issue key
ZOOKEEPER-2251    Critical
ZOOKEEPER-1940     Trivial
ZOOKEEPER-2306       Major
ZOOKEEPER-2391       Minor
ZOOKEEPER-2524       Major
ZOOKEEPER-1827       Major
ZOOKEEPER-2504       Major
ZOOKEEPER-1948       Major
ZOOKEEPER-2448       Major
ZOOKEEPER-2720       Major
ZOOKEEPER-2312       Minor
ZOOKEEPER-2627       Major
ZOOKEEPER-1787       Minor
ZOOKEEPER-2414    Critical
ZOOKEEPER-1784       Major
ZOOKEEPER-2636     Blocker
ZOOKEEPER-2665       Major
ZOOKEEPER-2763       Minor
ZOOKEEPER-2158       Major
ZOOKEEPER-2262       Major
ZOOKEEPER-2056       Major
ZOOKEEPER-2286       Minor
ZOOKEEPER-2160     Trivial
ZOOKEEPER-2256       Minor
ZOOKEEPER-2325    Critical
ZOOKEEPER-2650       Major
ZOOKEEPER-2661       Major
ZOOKEEPER-2111       Major
ZOOKEEPER-2169       Major
ZOOKEEPER-2385     Blocker
                    ...   
ZOOKEEPER-2457       Major
ZOOKEEPER-1864       Major
ZOOKEEPER-2465     Blocker
ZOOKEEPER-1836     Trivial
ZOOKEEPER-2164       Major
ZOOKEEPER-1997    

In [82]:
for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_test[i], y_pred_class[ i])
    roc_auc[i] = auc(fpr[i], tpr[i])

TypeError: Singleton array 'Major' cannot be considered a valid collection.